let p=structuredClone(DEFAULT),latest=null,candidate=null,activeStep=0,onlyFailures=false,dimRow=-1;
try { const saved=document.getElementById('initialState').textContent; if(saved.trim())p=JSON.parse(saved) }catch{}

const $=id=>document.getElementById(id),fmt=(x,n=2)=>Number.isFinite(x)?x.toLocaleString('en-US',{minimumFractionDigits:n,maximumFractionDigits:n}):'—',esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const specs={b:['梁寬 b','cm',10,200,1],h:['梁深 h','cm',20,300,1],cover:['保護層（至箍筋外緣）','cm',2,15,.1],agg:['粗粒料最大粒徑','cm',.5,5,.1],fc:['混凝土 f′c','kgf/cm²',210,560,10],fy:['主筋 fy','kgf/cm²',2800,5600,100],Es:['鋼筋 Es','kgf/cm²',1900000,2100000,10000],L:['分析跨度 L','m（用於內力與撓度）',.5,40,.1],Ln:['支承面間淨跨 Ln','m（用於深梁判別）',.5,40,.1],D:['額外靜載重 D','tf/m，不含梁自重',0,100,.1],LL:['活載重 L','tf/m',0,100,.1],Mu:['設計彎矩 |Mu|','tf·m，已因數化',0,10000,.1],Vu:['設計剪力 |Vu|','tf，已因數化',0,10000,.1],legs:['箍筋有效肢數','支',2,8,1],s:['箍筋間距 s','cm',2,100,1],fyt:['箍筋 fyt','kgf/cm²',2800,4200,100],sustain:['活載持續比例','0–1',0,1,.05]};
function field(k){let [title,unit,min,max,step]=specs[k];return `<label>${title}<small>${unit}</small><input id="${k}" type="number" value="${p[k]}" min="${min}" max="${max}" step="${step}" data-key="${k}"></label>`}
function select(k,title,values){return `<label>${title}<select id="${k}" data-key="${k}">${values.map(([v,t])=>`<option value="${v}" ${p[k]==v?'selected':''}>${t}</option>`).join('')}</select></label>`}
function init(){ $('sectionFields').innerHTML=['b','h','cover','agg','fc','fy','Es'].map(field).join('');$('loadFields').innerHTML=['L','Ln','D','LL','Mu','Vu'].map(field).join('');$('shearFields').innerHTML=select('stir','箍筋號數',[3,4,5].map(x=>[x,'#'+x]))+['legs','s','fyt'].map(field).join('');$('serviceFields').innerHTML=field('sustain')+select('xi','載重持續時間',[[1,'3 個月 / ξ=1.0'],[1.2,'6 個月 / ξ=1.2'],[1.4,'12 個月 / ξ=1.4'],[2,'5 年以上 / ξ=2.0']])+select('defLimit','附屬構材撓度限制',[[480,'易受損 / L÷480'],[240,'不易受損 / L÷240']]);$('mode').value=p.mode;$('dir').value=p.dir;$('designBar').innerHTML=Object.keys(BARS).filter(x=>x>=5).map(x=>`<option value="${x}" ${x==8?'selected':''}>#${x} · ${BARS[x].a} cm²/支</option>`).join('');renderRows();setMode();setStep(activeStep);update()}
function renderRows(){ $('rows').innerHTML=p.rows.map((r,i)=>`<div class="row-editor"><div class="row-head"><strong>第 ${i+1} 排</strong><button data-remove="${i}" aria-label="移除第 ${i+1} 排">移除</button></div><div class="row-grid"><label>基準梁面<select data-row="${i}" data-prop="face"><option value="bottom" ${r.face==='bottom'?'selected':''}>下緣</option><option value="top" ${r.face==='top'?'selected':''}>上緣</option></select></label><label>鋼筋號數<select data-row="${i}" data-prop="bar">${Object.keys(BARS).map(x=>`<option value="${x}" ${r.bar==x?'selected':''}>#${x}</option>`).join('')}</select></label><label>根數<input type="number" min="1" max="30" step="1" value="${r.n}" data-row="${i}" data-prop="n"></label><label>向內移動量 cm<input type="number" min="0" step=".1" value="${r.offset}" data-row="${i}" data-prop="offset"></label></div><div class="row-info" id="rowInfo${i}"></div></div>`).join('')}
function setMode(){let u=p.mode==='udl';['D','LL','L'].forEach(k=>$(k).closest('label').classList.toggle('hidden',!u));['Mu','Vu'].forEach(k=>$(k).closest('label').classList.toggle('hidden',u));$('serviceFields').classList.toggle('hidden',!u);$('dir').disabled=u;if(u){p.dir='positive';$('dir').value='positive'}}
function dimensionRow(r){if(dimRow<0||dimRow>=r.rows.length){const target=r.rows.filter(x=>x.face===(p.dir==='negative'?'top':'bottom'));return target.sort((a,b)=>b.offset-a.offset)[0]||r.rows[0]}return r.rows[dimRow]}
function svg(r){
 const selected=dimensionRow(r),all=dimRow<0,maxRows=Math.max(...['top','bottom'].map(face=>r.rows.filter(q=>q.face===face).length)),W=all?Math.max(460,350+maxRows*32):460,H=430,scale=Math.min(210/p.b,280/p.h),w=p.b*scale,h=p.h*scale,x=85+(210-w)/2,y=45,a=Math.min(r.a,p.h)*scale,negative=p.dir==='negative',blockY=negative?y+h-a:y,cy=negative?y+h-r.c*scale:y+r.c*scale;
 const sy=y+selected.y*scale,baseY=selected.face==='top'?y:y+h,dimX=x+w+32,dist=selected.face==='top'?selected.y:p.h-selected.y;
 const dim=(x1,y1,x2,y2,color)=>`<path d="M${x1} ${y1}L${x2} ${y2}" stroke="${color}" stroke-width="1.2" marker-start="url(#dimArrow)" marker-end="url(#dimArrow)"/>`;
 let out=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="梁斷面：第 ${selected.i+1} 排鋼筋中心距${selected.face==='top'?'上':'下'}緣 ${fmt(dist)} 公分"><defs><pattern id="grid" width="15" height="15" patternUnits="userSpaceOnUse"><path d="M15 0H0V15" fill="none" stroke="#e2eaf1" stroke-width=".5"/></pattern><marker id="dimArrow" viewBox="0 0 8 8" refX="4" refY="4" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M8 0L0 4L8 8" fill="none" stroke="#ab2867" stroke-width="1.2"/></marker></defs><rect width="${W}" height="430" fill="url(#grid)"/><text x="20" y="24" font-size="14" fill="#355773">${negative?'上緣':'下緣'}受拉 · 尺寸單位 cm</text><rect x="${x}" y="${y}" width="${w}" height="${h}" fill="#e4ebf0" stroke="#2e526c" stroke-width="2"/><rect x="${x}" y="${blockY}" width="${w}" height="${a}" fill="#ffc976" opacity=".65"/><rect x="${x+p.cover*scale}" y="${y+p.cover*scale}" width="${w-2*p.cover*scale}" height="${h-2*p.cover*scale}" rx="5" fill="none" stroke="#4d7b8e" stroke-width="2"/>`;
 r.rows.forEach(row=>{const inset=p.cover+BARS[p.stir].d+row.db/2;for(let i=0;i<row.n;i++){const bx=row.n===1?p.b/2:inset+(p.b-2*inset)*i/(row.n-1);out+=`<circle cx="${x+bx*scale}" cy="${y+row.y*scale}" r="${Math.max(3,row.db*scale/2)}" fill="${(all||row.i===selected.i)?'#ab2867':row.z>r.c?'#007d83':'#415b75'}" stroke="white" stroke-width="1"/>`}});
 out+=`<path d="M${x-9} ${cy}H${x+w+9}" stroke="#b77723" stroke-dasharray="5 4"/><text x="${x+4}" y="${Math.max(y+15,cy-7)}" font-size="12" fill="#85561d">c = ${fmt(r.c)}</text>`;
 // Full depth / full width, then the selected bar centroid to its reference face.
 out+=`<path d="M${x-8} ${y}H${x-40}M${x-8} ${y+h}H${x-40}M${x-32} ${y}V${y+h}" stroke="#648196" fill="none"/><path d="M${x-37} ${y+5}L${x-27} ${y-5}M${x-37} ${y+h+5}L${x-27} ${y+h-5}" stroke="#648196"/><text x="${x-46}" y="${y+h/2}" text-anchor="middle" transform="rotate(-90 ${x-46} ${y+h/2})" font-size="14" fill="#355773">h = ${fmt(p.h)}</text><path d="M${x} ${y+h+10}V${y+h+40}M${x+w} ${y+h+10}V${y+h+40}M${x} ${y+h+30}H${x+w}" stroke="#648196" fill="none"/><path d="M${x-5} ${y+h+35}L${x+5} ${y+h+25}M${x+w-5} ${y+h+35}L${x+w+5} ${y+h+25}" stroke="#648196"/><text x="${x+w/2}" y="${y+h+54}" text-anchor="middle" font-size="14" fill="#355773">b = ${fmt(p.b)}</text>`;
 if(all){
 for(const face of ['top','bottom']){
 const list=r.rows.filter(row=>row.face===face).sort((u,v)=>(face==='top'?u.y:p.h-u.y)-(face==='top'?v.y:p.h-v.y));
 list.forEach((row,j)=>{const yy=y+row.y*scale,base=face==='top'?y:y+h,xx=x+w+24+j*32,dd=face==='top'?row.y:p.h-row.y,mid=(yy+base)/2;
 out+=`<path d="M${x+w+4} ${yy}H${xx+6}M${x+w+4} ${base}H${xx+6}" stroke="#ab2867" opacity=".6" stroke-dasharray="3 3"/>${dim(xx,yy,xx,base,'#ab2867')}<text x="${xx+7}" y="${mid}" text-anchor="middle" transform="rotate(-90 ${xx+7} ${mid})" font-size="14" font-weight="600" fill="#ab2867" stroke="#f5f9fc" stroke-width="3" paint-order="stroke">${fmt(dd)}</text><text x="${x-7}" y="${yy+4}" text-anchor="end" font-size="12" fill="#ab2867">R${row.i+1}</text>`;
 });if(list.length)out+=`<text x="${x+w+16}" y="${face==='top'?y-12:y+h+23}" font-size="13" fill="#ab2867">至${face==='top'?'梁頂':'梁底'}</text>`;
 }
 out+=`<text x="20" y="411" font-size="13" fill="#ab2867">R = 輸入筋排編號 · 各尺寸均量至鋼筋中心</text>`;
 }else{
 out+=`<path d="M${x} ${sy}H${dimX+8}M${x+w+5} ${baseY}H${dimX+8}" stroke="#ab2867" stroke-dasharray="4 3" opacity=".8"/>${dim(dimX,sy,dimX,baseY,'#ab2867')}<text x="${dimX+12}" y="${(sy+baseY)/2-7}" font-size="13" fill="#ab2867">距${selected.face==='top'?'上':'下'}緣</text><text x="${dimX+12}" y="${(sy+baseY)/2+13}" font-size="18" font-weight="700" fill="#ab2867">${fmt(dist)}</text><text x="20" y="411" font-size="13" fill="#ab2867">第 ${selected.i+1} 排 · ${selected.n}-#${selected.bar} · 標註至鋼筋中心</text>`;
 }
 out+='</svg>';
 return out;
}
function dimensionNote(r){const sorted=[...r.rows].sort((a,b)=>a.y-b.y);return `<b>各筋排距離（cm）</b><div class="table-wrap"><table class="dim-table"><thead><tr><th>筋排</th><th>距梁頂</th><th>距梁底</th><th>排內淨距</th></tr></thead><tbody>${r.rows.map(row=>`<tr><td>R${row.i+1} · ${row.n}-#${row.bar}</td><td>${fmt(row.y)}</td><td>${fmt(p.h-row.y)}</td><td>${isFinite(row.space)?fmt(row.space):'單根'}</td></tr>`).join('')}</tbody></table></div>${sorted.length>1?`<div class="table-wrap"><table class="dim-table"><thead><tr><th>相鄰筋排</th><th>中心距</th><th>垂直淨距</th></tr></thead><tbody>${sorted.slice(1).map((row,i)=>{const prev=sorted[i],gap=row.y-prev.y;return `<tr><td>R${prev.i+1}–R${row.i+1}</td><td>${fmt(gap)}</td><td>${fmt(gap-(row.db+prev.db)/2)}</td></tr>`}).join('')}</tbody></table></div>`:''}<span>距梁面 = 保護層 ${fmt(p.cover)} + 箍筋直徑 ${fmt(BARS[p.stir].d,3)} + 各排主筋半徑 + 內移量。<br>中心距為兩排中心間距；淨距另扣除兩排主筋半徑。</span>`}
function metric(title,capacity,demand,unit){const ratio=demand/capacity;return `<div class="metric"><div class="label">${title}</div><div class="value">${fmt(capacity)} <small>${unit}</small></div><div class="meter"><span style="width:${Math.min(100,ratio*100)}%;background:${ratio>1?'#bd444c':'#007d83'}"></span></div><div class="sub">需求 ${fmt(demand)} · 利用率 ${fmt(ratio*100,0)}%</div></div>`}
function val(c){const v=c.value;if(v.text)return esc(v.text);const minimum=['拉力控制','最小受拉鋼筋','最小箍筋量','室內梁保護層'].includes(c.name),strength=['彎矩強度','剪力強度'].includes(c.name),digits=c.name==='拉力控制'?5:2;return `<div class="comparison"><span>${minimum?'實配 / 實際':strength?'需求':'實際'} <b>${fmt(minimum?v.capacity:v.demand,digits)}</b></span><span>${minimum?'最小需求':strength?'可用強度':'容許上限'} <b>${fmt(minimum?v.demand:v.capacity,digits)}</b></span><small>${v.unit}</small></div>`}
const fixes={彎矩強度:[2,'增加受拉鋼筋或梁深，並重新檢查拉力控制。'],拉力控制:[0,'增加梁寬或梁深，或減少過量受拉鋼筋。'],最小受拉鋼筋:[2,'增加受拉面主筋至最小配筋量。'],剪力強度:[3,'調整箍筋間距／肢數；超過斷面上限時須增大梁斷面。'],最小箍筋量:[3,'縮小箍筋間距，或增加有效肢數。'],箍筋縱向間距:[3,'箍筋間距須不大於列示上限。'],箍筋橫向肢距:[3,'增加箍筋有效肢數，並確認各肢錨定細節。'],主筋水平淨距:[2,'減少每排根數、改分排或增加梁寬。'],主筋垂直淨距:[2,'增大筋排內移量差；仍須確認各排上下對齊。'],室內梁保護層:[0,'非暴露環境現場澆置梁採至少 4 cm。'],樓層活載即時撓度:[0,'優先增加梁深，並核對跨度與服務載重。'],附屬構材後續撓度:[0,'檢查梁深、持續載重比例與附屬構材容許值。']};
function setStep(i){activeStep=i;document.querySelectorAll('.inputs > .panel').forEach((el,j)=>{el.classList.toggle('hidden',i!==j);el.id='inputPanel'+j;el.setAttribute('role','tabpanel');el.setAttribute('aria-labelledby','inputTab'+j)});document.querySelectorAll('[data-step]').forEach((el,j)=>{el.classList.toggle('selected',i===j);el.id='inputTab'+j;el.setAttribute('aria-controls','inputPanel'+j);el.tabIndex=i===j?0:-1;el.setAttribute('aria-selected',String(i===j))})}
function goStep(i){setView('workspace');setStep(i);document.querySelector('.inputs').scrollIntoView({behavior:'smooth',block:'start'})}
function checkRows(r){return r.checks.filter(c=>!onlyFailures||!c.ok).map(c=>`<tr class="${c.ok?'':'failed-row'}"><td>${c.name}<small>${c.clause}</small></td><td>${val(c)}</td><td><span class="pill ${r.scopeIssues.length?'warn':c.ok?'':'bad'}">${r.scopeIssues.length?'參考':c.ok?'通過':'未通過'}</span></td></tr>`).join('')||'<tr><td colspan="3">目前沒有未通過的計算項目。</td></tr>'}
function update(){candidate=null;$('designResult').textContent='固定另一側配筋，以 1–3 排、每排 2–12 支搜尋最小面積可行配置。';try{const r=analyze(p);latest=r;const failures=r.checks.filter(x=>!x.ok).length;$('loadNote').innerHTML=p.mode==='udl'?`梁自重 = ${p.b/100} × ${p.h/100} × 2.4 = <b>${fmt(r.self,3)} tf/m</b><br>總 D = ${fmt(p.D)} + ${fmt(r.self,3)} = ${fmt(r.Dtot,3)} tf/m<br>wu = max(1.4D, 1.2D + 1.6L) = <b>${fmt(r.wu,3)} tf/m</b>`:'直接採用所輸入之設計內力；不另加梁自重或載重因數。';
 const notices=[...r.scopeIssues];if(p.mode==='direct')notices.push('直接內力模式：撓度、集中載重位置及不連續區另行檢核。');const pending=notices.length>0;const statusText=r.scopeIssues.length?'有適用範圍待確認':failures?failures+' 項檢核未通過':pending?'斷面檢核通過・尚有待核項目':'已列 '+r.checks.length+' 項檢核通過';
 $('results').innerHTML=`<div class="result-summary"><div class="status ${r.scopeIssues.length?'warn':failures?'bad':pending?'warn':''}"><div><strong>${statusText}</strong><small>僅限本工具列示項目；耐震、錨定等仍須另檢核。</small></div><span>${r.scopeIssues.length?'參考試算':failures?'需調整':pending?'待確認':'已更新'}</span></div><div class="metrics">${metric('設計彎矩強度 φMn',r.cap,r.Mu,'tf·m')}${metric('設計剪力強度 φVn',r.Vcap,r.Vu,'tf')}${p.mode==='udl'?metric('後續撓度容許值',p.L*100/p.defLimit,r.deltaAfter,'cm'):`<div class="metric"><div class="label">撓度檢核</div><div class="value" style="font-size:22px">未計算</div><div class="sub">直接內力模式</div></div>`}</div></div>${failures?`<section class="issue-list"><h3>優先調整 ${failures} 項</h3>${r.checks.filter(c=>!c.ok).map(c=>`<button data-fix="${fixes[c.name]?.[0]||0}"><b>${c.name}</b><span>${fixes[c.name]?.[1]||'檢查參數'}</span><em>前往調整</em></button>`).join('')}</section>`:''}<div class="scope">一般矩形 RC 梁 · 臺灣 112 年規範／113 年勘誤<br>純彎、常重混凝土；不含耐震梁端、軸力及扭力。${notices.length?'<br><b>'+notices.join(' ')+'</b>':''}</div><section class="panel"><h2>斷面與受力狀態</h2><div class="split"><div class="figure"><label class="dim-selector">尺寸標註<select id="dimSelect"><option value="-1" ${dimRow<0?'selected':''}>全部筋排（同時顯示）</option>${r.rows.map(row=>`<option value="${row.i}" ${dimRow>=0&&row.i===dimensionRow(r).i?'selected':''}>第 ${row.i+1} 排｜${row.face==='top'?'上緣':'下緣'} ${row.n}-#${row.bar}</option>`).join('')}</select></label><div id="dimensionSvg">${svg(r)}</div><div class="dimension-note" id="dimensionNote">${dimensionNote(r)}</div><div class="legend">青色：受拉鋼筋　橘色：等值壓力塊<br>虛線：極限中性軸；圖按比例繪製</div></div><div class="mini-grid">${[['有效深度 d',fmt(r.d)+' cm'],['受拉面主筋 As',fmt(r.As)+' cm²'],['中性軸 c',fmt(r.c)+' cm'],['壓力塊 a',fmt(r.a)+' cm'],['拉應變 εt',fmt(r.et,5)],['折減因數 φ',fmt(r.phi,3)],['設計 Mu',fmt(r.Mu)+' tf·m'],['設計 Vu',fmt(r.Vu)+' tf']].map(([a,b])=>`<div class="mini"><span>${a}</span><strong>${b}</strong></div>`).join('')}</div></div></section><section class="panel"><div class="section-heading"><h2>逐項檢核結果</h2><button id="filterChecks" aria-pressed="${onlyFailures}">${onlyFailures?'顯示全部':'只看未通過'}</button></div><div class="table-wrap"><table class="checks"><thead><tr><th>檢核項目／依據</th><th>實際 / 需求對照</th><th>判定</th></tr></thead><tbody>${checkRows(r)}</tbody></table></div><p class="hint">≥ 與 ≤ 邊界均採包含等號；負值、空白、超出適用範圍會停止計算，不保留舊結果。</p></section>`;
 $('dimSelect').onchange=e=>{dimRow=+e.target.value;$('dimensionSvg').innerHTML=svg(latest);$('dimensionNote').innerHTML=dimensionNote(latest)};
 $('filterChecks').onclick=()=>{onlyFailures=!onlyFailures;update()};
 document.querySelectorAll('[data-fix]').forEach(b=>b.onclick=()=>goStep(+b.dataset.fix));
 r.rows.forEach(row=>{const el=$('rowInfo'+row.i);if(el)el.textContent=`As = ${fmt(row.A)} cm² · 中心距基準面 ${fmt(row.face==='top'?row.y:p.h-row.y)} cm · 淨距 ${isFinite(row.space)?fmt(row.space)+' cm':'單根'}`});
 $('inputSummary').textContent=`${p.b} × ${p.h} cm · ${p.mode==='udl'?'簡支均布載重':'直接設計內力'} · ${p.rows.length} 排主筋`;
 $('mobileResult').innerHTML=`<a href="#results">${r.scopeIssues.length?'待核適用範圍':failures?failures+' 項未通過':'查看計算結果'} · φMn ${fmt(r.cap)} tf·m</a>`;
 $('appStatus').textContent=statusText+' · 即時更新'; renderCalcs(r);
 }catch(e){$('appStatus').textContent='輸入有誤 · 請修正參數';latest=null;document.querySelectorAll('.row-info').forEach(x=>x.textContent='資料待修正');$('mobileResult').innerHTML='<a href="#results">輸入有誤・查看原因</a>';$('results').innerHTML=`<div class="error"><strong>請修正輸入資料</strong><p>${esc(e.message)}</p><small>已停止檢核；下方不顯示上一次結果。</small></div>`;$('calculations').textContent='輸入資料尚未有效，無法產生計算書。';$('loadNote').textContent='資料待修正。'}}
function renderCalcs(r){const rowTable=`<div class="table-wrap"><table class="checks"><thead><tr><th>排／配置</th><th>As / z</th><th>εs</th><th>fs</th><th>淨力 F</th></tr></thead><tbody>${r.steels.map(s=>`<tr><td>${s.i+1}：${s.n}-#${s.bar}<small>${s.face==='top'?'上緣':'下緣'}，內移 ${s.offset} cm</small></td><td>${fmt(s.A)} cm²<br>${fmt(s.z)} cm</td><td>${fmt(s.eps,6)}</td><td>${fmt(s.fs,1)} kgf/cm²</td><td>${fmt(s.F/1000,3)} tf</td></tr>`).join('')}</tbody></table></div>`;
 $('calculations').innerHTML=`<details open><summary>1. 輸入摘要與設計內力</summary><div class="formula">b × h = ${p.b} × ${p.h} cm；保護層 ${p.cover} cm；f′c = ${p.fc}、fy = ${p.fy}、Es = ${fmt(p.Es,0)} kgf/cm²<br>淨跨 Ln = ${p.Ln} m；箍筋 ${p.legs} 肢 #${p.stir} @ ${p.s} cm；fyt = ${p.fyt} kgf/cm²；粒徑 ${p.agg} cm<br>${p.mode==='udl'?`L = ${p.L} m；額外 D = ${p.D} tf/m；活載 = ${p.LL} tf/m<br>梁自重 = bh × 2.4 / 10,000 = ${fmt(r.self,3)} tf/m；總 D = ${fmt(r.Dtot,3)} tf/m<br>1.4D = ${fmt(1.4*r.Dtot,3)}；1.2D + 1.6L = ${fmt(1.2*r.Dtot+1.6*p.LL,3)} tf/m<br>Mu = wu L²/8 = <b>${fmt(r.Mu,3)} tf·m</b>；Vu = wu L/2 = <b>${fmt(r.Vu,3)} tf</b>`:`直接輸入：Mu = <b>${p.Mu} tf·m</b>；Vu = <b>${p.Vu} tf</b>；${p.dir==='positive'?'下緣':'上緣'}受拉。`}</div></details>
<details><summary>2. 應變相容、力平衡與彎矩強度</summary><div class="formula">β₁ = max[0.65, min(0.85, 0.85 − 0.05(f′c−280)/70)] = ${fmt(r.beta,4)}<br>εcu = 0.003；a = β₁c = ${fmt(r.a,4)} cm<br>εs,i = 0.003(c−zi)/c；fs,i = 限幅(Es εs,i, −fy, +fy)<br>Fc = 0.85f′c ba = ${fmt(r.Cc/1000,4)} tf<br>Fi = Asi fs,i − 0.85f′c Aoverlap,i；Mi = Asi fs,i zi − 0.85f′c Qoverlap,i<br>求解 Fc + ΣFi = 0 → <b>c = ${fmt(r.c,5)} cm</b><br>力平衡殘差 = ${r.residual.toExponential(3)} kgf（正值為壓力）</div>${rowTable}<div class="formula">z 由受壓面量至筋排中心；壓應力為正、拉應力為負。以鋼筋圓形與壓力塊的實際相交面積及一次矩扣除置換混凝土，避免壓力塊切過筋排時產生數值跳動。<br>Mn = |Fc·a/2 + ΣMi| / 100,000 = <b>${fmt(r.Mn,4)} tf·m</b><br>εty = fy/Es = ${fmt(r.ey,6)}；εt = 0.003(dt−c)/c = ${fmt(r.et,6)}<br>φ = 限幅[0.65 + 0.25(εt−εty)/0.003, 0.65, 0.90] = ${fmt(r.phi,4)}<br>φMn = <b>${fmt(r.cap,4)} tf·m</b>；Mu = ${fmt(r.Mu,4)} tf·m<br>梁另須 εt ≥ εty + 0.003 = ${fmt(r.ey+.003,6)}，過渡區即使強度足夠仍判為不通過。</div></details>
<details><summary>3. 鋼筋量、幾何及箍筋</summary><div class="formula">As、d 採所選受拉面主筋，避免另一面少量受拉筋誤增設計配筋量。<br>d = ΣAs,t·zt / ΣAs,t = ${fmt(r.d,4)} cm；As = ${fmt(r.As,4)} cm²<br>As,min = max(0.8√f′c, 14)bd/min(fy,5600) = <b>${fmt(r.Asmin,4)} cm²</b><br>水平淨距 = [b−2(cover+db,hoop)−n·db]/(n−1)<br>需求水平淨距 ≥ max(2.5 cm, db, 4dagg/3)<br>Av = 肢數 × 單支箍筋面積 = ${fmt(r.Av,4)} cm²<br>Av,min/s = max(0.2√f′c,3.5)b/fyt → Av,min = ${fmt(r.Avmin,4)} cm²<br>ρw = As/(bd) = ${fmt(r.rho,6)}；λs = min[1,√(2/(1+d/25))] = ${fmt(r.lambdaS,4)}<br>本例 Vc 分支：${r.Av>=r.Avmin?'Av ≥ Av,min，Vc = 0.53√f′c bd':'Av &lt; Av,min，Vc = min(2.12λsρw^(1/3),1.33)√f′c bd'}<br>Vc = <b>${fmt(r.Vc,4)} tf</b>；Vs = Av fyt d/s = <b>${fmt(r.Vs,4)} tf</b><br>Vs,req = max(Vu/0.75 − Vc,0) = ${fmt(r.Vsreq,4)} tf<br>斷面剪力上限 = 0.75(Vc + 2.12√f′c bd) = ${fmt(r.Vmax,4)} tf<br>可用剪力強度 = min[0.75(Vc+Vs), 斷面上限] = <b>${fmt(r.Vcap,4)} tf</b><br>沿長度 s 上限 = ${fmt(r.smax)} cm；沿寬度肢距上限 = ${fmt(r.widthMax)} cm<br>箍筋間距初估 ≤ ${fmt(r.sRecommend,2)} cm（調整後須重算，因分支與間距上限可能改變）。</div></details>
<details><summary>4. 開裂與撓度計算</summary>${p.mode==='udl'?`<div class="formula">Ec = 12,000√f′c = ${fmt(r.Ec,1)} kgf/cm²；n = Es/Ec = ${fmt(r.n,4)}<br>Ig = bh³/12 = ${fmt(r.Ig,1)} cm⁴；fr = 2√f′c = ${fmt(2*Math.sqrt(p.fc),4)} kgf/cm²<br>Mcr = fr Ig/(h/2) = <b>${fmt(r.Mcr,4)} tf·m</b><br>開裂中性軸 k：bk²/2 + Σni Asi(k−zi) = 0 → k = ${fmt(r.kd,4)} cm<br>壓區 ni = n−1；拉區 ni = n。Icr = bk³/3 + Σni Asi(zi−k)² = ${fmt(r.Icr,1)} cm⁴<br>Ma ≤ 2Mcr/3：Ie = Ig；其他：Ie = Icr / {1 − [2Mcr/(3Ma)]²(1−Icr/Ig)}<br>本例 Ma(D+L) = ${fmt((r.Dtot+p.LL)*p.L*p.L/8,4)} tf·m → Ie = <b>${fmt(r.Ie,1)} cm⁴</b><br>δ(w) = 5wL⁴/(384EcIe)，w 轉 kgf/cm、L 轉 cm；各載重水準分別求 Ie<br>δD = ${fmt(r.deltaD,4)} cm；δD+L = ${fmt(r.deltaDL,4)} cm<br>δL = δD+L − δD = <b>${fmt(r.deltaLL,4)} cm</b>；容許 L/360 = ${fmt(p.L*100/360,4)} cm<br>持續載重 = D + ${p.sustain}L；δsus = ${fmt(r.deltaS,4)} cm<br>λΔ = ξ/(1+50ρ′) = ${fmt(r.lambdaD,4)}；ξ = ${p.xi}；ρ′採開裂壓區鋼筋面積／bd<br>額外依時撓度 = λΔδsus = ${fmt(r.deltaLong,4)} cm<br>保守後續撓度 = δL + λΔδsus = <b>${fmt(r.deltaAfter,4)} cm</b>；容許 L/${p.defLimit} = ${fmt(p.L*100/p.defLimit,4)} cm</div>`:'<p>直接內力模式無法由 Mu、Vu 唯一決定載重分布，故不提供撓度通過判定。</p>'}</details>`;
}
document.addEventListener('input',e=>{let t=e.target;if(t.dataset.key){p[t.dataset.key]=t.value===''?NaN:Number(t.value);update()}else if(t.dataset.row!==undefined){p.rows[+t.dataset.row][t.dataset.prop]=t.dataset.prop==='face'?t.value:(t.value===''?NaN:Number(t.value));update()}});
$('mode').onchange=e=>{p.mode=e.target.value;setMode();update()};$('dir').onchange=e=>{p.dir=e.target.value;update()};
$('rows').onclick=e=>{const b=e.target.closest('[data-remove]');if(b){p.rows.splice(+b.dataset.remove,1);renderRows();update()}};
$('addRow').onclick=()=>{if(p.rows.length>=6){toast('最多 6 排主筋');return}let face=p.dir==='negative'?'top':'bottom',existing=p.rows.filter(r=>r.face===face).sort((a,b)=>(a.offset+BARS[a.bar].d/2)-(b.offset+BARS[b.bar].d/2)),last=existing[existing.length-1],bar=last?.bar||8,db=BARS[bar].d;p.rows.push({face,n:2,bar,offset:last?last.offset+BARS[last.bar].d/2+db/2+2.5:0});renderRows();update()};
$('design').onclick=()=>{if(!latest){toast('請先修正輸入資料');return}const found=suggest(p,+$('designBar').value);candidate=found;$('designResult').innerHTML=found?`<b>建議：${found.layers} 排 × ${found.per}-#${found.bar}</b><br>受拉面配置面積 ${fmt(found.area)} cm²；φMn = ${fmt(found.r.cap)} tf·m。<br><span class="${found.r.ok?'':'design-warning'}">${found.r.ok?'已列計算項目皆通過。':'其他尚未通過：'+found.r.checks.filter(c=>!c.ok).map(c=>c.name).join('、')}</span><br>已檢查彎矩、拉力控制、最小筋量及淨距；套用後重新檢核剪力與撓度。<button id="applyDesign" class="primary" style="margin-top:10px">套用此配筋</button>`:'此號數在 1–3 排、每排 2–12 支的範圍內無可行解。請增加斷面、調整主筋號數或另一側鋼筋。';if(found)$('applyDesign').onclick=()=>{p.rows=structuredClone(candidate.rows);renderRows();update();toast('已套用配筋並重新檢核全部項目')}};
$('reset').onclick=()=>{if(!confirm('載入範例會取代目前所有參數，確定載入？'))return;p=structuredClone(DEFAULT);activeStep=0;dimRow=-1;init();toast('已載入 35 × 65 cm 範例')};
function toast(t){$('toast').textContent=t;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),2800)}
$('print').onclick=()=>{if(!latest){toast('請先修正資料再列印');return}document.querySelectorAll('#process details').forEach(x=>x.open=true);window.print()};
$('download').onclick=()=>{if(!latest){toast('請先修正輸入再下載');return}const clone=document.documentElement.cloneNode(true);clone.querySelector('#initialState').textContent=JSON.stringify(p).replace(/</g,'\\u003c');clone.querySelector('#toast').classList.add('hidden');const html='<!doctype html>\n'+clone.outerHTML;let url=URL.createObjectURL(new Blob([html],{type:'text/html;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='RC_Beam_Analysis_TW112_v1_4.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('已下載，離線開啟會保留目前參數')};
document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>setStep(+b.dataset.step));
document.querySelector('.input-tabs').onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const i=e.key==='Home'?0:e.key==='End'?3:(activeStep+(e.key==='ArrowRight'?1:3))%4;setStep(i);document.querySelector('[data-step="'+i+'"]').focus()}};
$('expandCalcs').onclick=()=>document.querySelectorAll('#process details').forEach(d=>d.open=true);
$('collapseCalcs').onclick=()=>document.querySelectorAll('#process details').forEach(d=>d.open=false);

function setView(view){
 document.body.dataset.view=view;
 $('workspace').classList.toggle('view-hidden',view==='process'||view==='basis');
 document.querySelectorAll('[data-view]').forEach(el=>{if(el===document.body)return;const on=el.dataset.view===view||(view==='results'&&el.closest('.app-nav')&&el.dataset.view==='workspace');el.classList.toggle('active',on);el.setAttribute('aria-pressed',String(on));});
}
document.querySelectorAll('button[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));
document.querySelectorAll('[data-command]').forEach(b=>b.onclick=()=>{b.closest('details').open=false;$(b.dataset.command).click()});
$('focusToggle').onclick=()=>{const on=document.body.classList.toggle('focus-mode');$('focusToggle').textContent=on?'顯示參數面板':'收合參數面板';$('focusToggle').setAttribute('aria-pressed',String(on))};
init();setView('workspace');

